export const SET_WEATHER_API_CONFIGURE: string = 'POST/SET_WEATHER_API_CONFIGURE'
export const FETCH_NEXT_DAYS_WEATHER: string = 'POST/FETCH_NEXT_DAYS_WEATHER'
export const REQUEST_NEXT_DAYS_WEATHER: string = 'POST/REQUEST_NEXT_DAYS_WEATHER' // for Redux saga
